### ISSUE TITLE
Blank "app_parameters" being passed while running examples

### ISSUE THREAD

**Issue by SanchiMittal** [alibaba/EasyNLP#214]
I am trying to run an example from [here](https://github.com/alibaba/EasyNLP/tree/master/examples/quick_start_user_defined). I am getting the following error, with both the gpu and cpu script. I tried printing the dictionary "app_parameters" from inside the library where it is throwing error, and indeed it is blank.

It also shows a warning saying `No module named 'easy_predict'`. I have used the setup.py in the root directory of this repository to install EasyNLP, hence I was expecting it to run smoothly. Please help me resolve this issue. Thanks!  

```
(easy-nlp) sanchi@DGX-Station:/raid/sanchi/EasyNLP/examples/quick_start_user_defined# sh run_user_defined_local_cpu.sh
**************************************************
running local main...

No module named 'easy_predict'
------------------------ arguments ------------------------
  app_name ........................................ text_classify
  append_cols ..................................... None
  buckets ......................................... None
  checkpoint_dir .................................. ./tmp/classification_model/
  chief_hosts .....................................
  data_threads .................................... 10
  distributed_backend ............................. nccl
  do_lower_case ................................... False
  epoch_num ....................................... 1.0
  export_tf_checkpoint_type ....................... easytransfer
  first_sequence .................................. sent1
  gradient_accumulation_steps ..................... 1
  input_schema .................................... label:str:1,sid1:str:1,sid2:str:1,sent1:str:1,sent2:str:1
  is_chief ........................................
  is_master_node .................................. True
  job_name ........................................ None
  label_enumerate_values .......................... 0,1
  label_name ...................................... label
  learning_rate ................................... 3e-05
  local_rank ...................................... None
  logging_steps ................................... 5
  master_port ..................................... 23456
  max_grad_norm ................................... 1.0
  micro_batch_size ................................ 4
  mode ............................................ train
  modelzoo_base_dir ...............................
  n_cpu ........................................... 1
  n_gpu ........................................... 0
  odps_config ..................................... None
  optimizer_type .................................. AdamW
  output_schema ...................................
  outputs ......................................... None
  predict_queue_size .............................. 1024
  predict_slice_size .............................. 4096
  predict_table_read_thread_num ................... 16
  predict_thread_num .............................. 2
  ps_hosts ........................................
  random_seed ..................................... 42
  rank ............................................ 0
  read_odps ....................................... False
  restore_works_dir ............................... ./.easynlp_predict_restore_works_dir
  resume_from_checkpoint .......................... None
  save_all_checkpoints ............................ False
  save_checkpoint_steps ........................... 50
  second_sequence ................................. sent2
  sequence_length ................................. 128
  skip_first_line ................................. False
  tables .......................................... tmp/train_toy.tsv,tmp/dev.tsv
  task_count ...................................... 1
  task_index ...................................... 0
  use_amp ......................................... False
  use_torchacc .................................... False
  user_defined_parameters ......................... pretrain_model_name_or_path=bert-small-uncased
  user_entry_file ................................. None
  user_script ..................................... None
  warmup_proportion ............................... 0.1
  weight_decay .................................... 0.0001
  worker_count .................................... 1
  worker_cpu ...................................... -1
  worker_gpu ...................................... 0
  worker_hosts .................................... None
  world_size ...................................... 1
-------------------- end of arguments ---------------------
> initializing torch distributed ...
Init dist done. World size: 1, rank 0, l_rank None
> setting random seeds to 42 ...
`/root/.easynlp/modelzoo/public/bert-small-uncased.tgz` already exists
log: starts to process user params...

pretrained_model_name_or_path /root/.easynlp/modelzoo/public/bert-small-uncased
log: starts to process dataset...


Traceback (most recent call last):
  File "/raid/sanchi/EasyNLP/examples/quick_start_user_defined/main.py", line 48, in <module>
    valid_dataset = ClassificationDataset(
  File "/home/sanchi/miniconda3/envs/easy-nlp/lib/python3.10/site-packages/pai_easynlp-0.0.7-py3.10.egg/easynlp/appzoo/sequence_classification/data.py", line 88, in __init__
    **print(user_defined_parameters.get('app_parameters'))
AttributeError: 'NoneType' object has no attribute 'get'**
```

**Comment by chywang** [comment]
would u look into this error pls @deplay

**Comment by SanchiMittal** [comment]
I found the issue in the main.py in `"EasyNLP/examples/quick_start_user_defined/main.py"`.  The `user_defined_parameters` variable is not passed to the validation data initialization, causing it to be set as `None` and error is being thrown. Should I open a PR and fix?

**Comment by chywang** [comment]
> I found the issue in the main.py in `"EasyNLP/examples/quick_start_user_defined/main.py"`. The `user_defined_parameters` variable is not passed to the validation data initialization, causing it to be set as `None` and error is being thrown. Should I open a PR and fix?

sure
