### ISSUE TITLE
Bug: TypeError: forward() got an unexpected keyword argument 'teacher_logits'

### ISSUE THREAD

**Issue by SanchiMittal** [alibaba/EasyNLP#221]
I am trying to run [this](https://github.com/alibaba/EasyNLP/blob/master/examples/knowledge_distillation/run_vanilla_kd.sh) vanilla example on meta KD. I am getting the following error, in the knowledge distillation part of the student model. It seems that during fine-tuning of Student model, the parameter `teacher_logits` is getting passed into the model forward pass, which shouldn't be there.

Error:
```
/home/sanchi/miniconda3/lib/python3.8/site-packages/pai_easynlp-0.0.7-py3.8.egg/easynlp/core/optimizers.py:441: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:1174.)
  exp_avg.mul_(beta1).add_(1.0 - beta1, grad)
/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:249: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "
[2022-09-28 10:05:18,552 INFO] Epoch [ 0/ 1], step [100/115], lr 0.000005, 6.34 s
[2022-09-28 10:05:18,552 INFO]   loss      : 0.5082 
Traceback (most recent call last):
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/pai_easynlp-0.0.7-py3.8.egg/easynlp/appzoo/api.py", line 530, in <module>
    default_main_fn()
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/pai_easynlp-0.0.7-py3.8.egg/easynlp/appzoo/api.py", line 507, in default_main_fn
    trainer.train()
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/pai_easynlp-0.0.7-py3.8.egg/easynlp/core/distiller.py", line 80, in train
    self.after_train()
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/pai_easynlp-0.0.7-py3.8.egg/easynlp/core/trainer.py", line 403, in after_train
    self._eval_scores = self.evaluator.evaluate(
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/pai_easynlp-0.0.7-py3.8.egg/easynlp/appzoo/text_match/evaluator.py", line 59, in evaluate
    outputs = model(batch)
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/pai_easynlp-0.0.7-py3.8.egg/easynlp/appzoo/text_match/model.py", line 60, in forward
    outputs = self.backbone(**inputs)
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
**TypeError: forward() got an unexpected keyword argument 'teacher_logits'**
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3853707) of binary: /home/sanchi/miniconda3/bin/python
Traceback (most recent call last):
  File "/home/sanchi/miniconda3/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sanchi/miniconda3/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sanchi/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

I tried to internally print the `distillation_parameters` from [this file](https://github.com/alibaba/EasyNLP/blob/master/easynlp/core/distiller.py#:~:text=distillation_params%5B%27teacher_logits,.after_train()), which is okay:
```
Distillation Prameters: {'enable_distillation': True, 'type': 'vanilla_kd', 'logits_name': 'logits', 'logits_saved_path': 'results/large-sst2-teacher/pred.tsv', 'temperature': 5.0, 'alpha': 0.2, 'teacher_logits': tensor([[-0.4423,  0.1519],
        [-1.2202,  1.1911],
        [-0.2366, -0.3059],
        [-0.4769,  0.2522],
        [-0.1601, -0.3526],
        [-0.8216,  0.7683],
        [-0.4401,  0.1457],
        [-0.6810,  0.6185],
        [-0.4969,  0.4187],
        [-1.2004,  1.1545],
        [-0.3606, -0.4883],
        [-0.4833,  0.3036],
        [-0.4924,  0.2782],
        [-1.1261,  1.0662],
        [-0.2079, -0.2397],
        [-0.1248, -0.2341],
        [-0.1677, -0.4931],
        [-0.5122,  0.4601],
        [-1.1436,  1.1654],
        [-0.7187,  0.5402]], device='cuda:0')}
```

And then I printed the first batch from [here](https://github.com/alibaba/EasyNLP/blob/master/easynlp/appzoo/text_match/evaluator.py#:~:text=outputs%20%3D%20model(batch)), and there also `teacher_logits` is present:
```
Step 0 batch: {'input_ids': tensor([[  101,  2002,  2056,  ...,     0,     0,     0],
        [  101, 20201, 22948,  ...,     0,     0,     0],
        [  101,  1996,  7922,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2523,  ...,     0,     0,     0],
        [  101,  2007,  2122,  ...,     0,     0,     0],
        [  101, 13420,  2001,  ...,     0,     0,     0]], device='cuda:0'), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0'), 'teacher_logits': tensor([[-1.0395,  0.8159],
        [-0.2145, -0.0592],
        [-1.1646,  1.1143],
        [-0.2077, -0.2372],
        [-0.1383, -0.4178],
        [-0.5489,  0.3512],
        [-0.1469, -0.5487],
        [-0.2306, -0.1807],
        [-0.2887, -0.4355],
        [-0.3262, -0.0953],
        [-0.9406,  0.8549],
        [-0.1969, -0.5288],
        [-0.9336,  0.6801],
        [-1.1936,  1.2028],
        [-0.2827, -0.4389],
        [-0.1474, -0.0258],
        [-0.7127,  0.5148],
        [-1.0226,  0.8398],
        [-0.1122, -0.0246],
        [-1.0677,  0.8637],
        [-0.1015, -0.0428],
        [-0.0625, -0.1809],
        [-0.7062,  0.4776],
        [-1.0694,  0.9552],
        [-0.6102,  0.3898],
        [-0.9585,  0.7841],
        [-0.1003, -0.4704],
        [-0.1608, -0.1917],
        [-0.3235,  0.0344],
        [-0.2024, -0.4368],
        [-0.5087,  0.2350],
        [-0.2400, -0.4008]], device='cuda:0')}
```
Teacher model fine-tuning and logits saving are working fine, error comes in student fine-tuning. I can share the complete logs including teacher model training and inference, if needed. Please help me resolve this issue, thanks.

**Comment by chywang** [comment]
thank you for the issue, we will look into it asap. @ztl-35

**Comment by chywang** [comment]
this problem has been solved. see newest pull request
