### ISSUE TITLE
./run_fewshot_cpt.sh  ERROR

### ISSUE THREAD

**Issue by wpfnlp** [alibaba/EasyNLP#63]
TypeError: type object got multiple values for keyword argument 'user_defined_parameters'

Using Contrastive Few shot Learner, using random label words only as place-holders
Traceback (most recent call last):
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py", line 459, in <module>
    default_main_fn()
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py", line 423, in default_main_fn
    evaluator = get_application_evaluator(
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py", line 303, in get_application_evaluator
    return evaluator[key](valid_dataset, user_defined_parameters=user_defined_parameters, **kwargs)
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/fewshot_learning/fewshot_evaluator.py", line 131, in __init__
    anchor_dataset = FewshotBaseDataset(
TypeError: type object got multiple values for keyword argument 'user_defined_parameters'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 209685) of binary: /home/wpf/anaconda3/envs/fewshot/bin/python
Traceback (most recent call last):
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
*********************************************************************************************
  /home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py FAILED  
=============================================================================================
Root Cause:
[0]:
  time: 2022-04-28_19:18:11
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 209685)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=============================================================================================

**Comment by minghui** [comment]
@chywang pls take a look~

**Comment by chywang** [comment]
> TypeError: type object got multiple values for keyword argument 'user_defined_parameters'
> 
> Using Contrastive Few shot Learner, using random label words only as place-holders Traceback (most recent call last): File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py", line 459, in default_main_fn() File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py", line 423, in default_main_fn evaluator = get_application_evaluator( File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py", line 303, in get_application_evaluator return evaluator[key](valid_dataset, user_defined_parameters=user_defined_parameters, **kwargs) File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/fewshot_learning/fewshot_evaluator.py", line 131, in **init** anchor_dataset = FewshotBaseDataset( TypeError: type object got multiple values for keyword argument 'user_defined_parameters' ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 209685) of binary: /home/wpf/anaconda3/envs/fewshot/bin/python Traceback (most recent call last): File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in main() File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main launch(args) File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch run(args) File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run elastic_launch( File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "/home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent raise ChildFailedError( torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> 
> # /home/wpf/anaconda3/envs/fewshot/lib/python3.8/site-packages/easynlp/appzoo/api.py FAILED
> # Root Cause:
> [0]:
> time: 2022-04-28_19:18:11
> rank: 0 (local_rank: 0)
> exitcode: 1 (pid: 209685)
> error_file: <N/A>
> msg: "Process failed with exitcode 1"

what is your command?
